import sqlite3

DB_PATH = "pff.db"

connection = sqlite3.connect(DB_PATH)
cursor = connection.cursor()

def create_play_command():
    return """
    CREATE TABLE play (
        play_id INTEGER PRIMARY KEY,
        game_id INTEGER,
        gsis_play_id INTEGER,
        quarter INTEGER,
        down INTEGER,
        clock STRING,
        blitz_dog INTEGER,
        catchable INTEGER,
        deep_pass INTEGER,
        def_score INTEGER,
        draw INTEGER,
        drive INTEGER,
        drive_play INTEGER,
        gain_loss_net INTEGER,
        garbage_time INTEGER,
        get_off_time REAL,
        kick_yards INTEGER,
        no_huddle INTEGER,
        no_play INTEGER,
        unbalanced INTEGER,
        off_score INTEGER,
        option INTEGER,
        penalty_yards INTEGER,
        play_action INTEGER,
        previous_play_id INTEGER,
        return_yards INTEGER,
        score REAL,
        screen INTEGER,
        snap_time REAL,
        sort_order INTEGER,
        stunt INTEGER,
        time_to_pressure REAL,
        time_to_throw REAL,
        trick_look INTEGER,
        trick_play INTEGER,
        yards_after_catch INTEGER,
        yards_after_contact INTEGER,
        two_minute INTEGER,
        ball_carrier TEXT,
        box_players TEXT,
        bunched_players TEXT,
        center_pass_block_direction TEXT,
        check_route TEXT,
        chip_route TEXT,
        defensive_back_depth TEXT,
        defensive_front TEXT,
        defensive_personnel TEXT,
        defensive_players TEXT,
        defensive_players_with_ratings TEXT,
        defensive_substitutions TEXT,
        defensive_success TEXT,
        defense TEXT,
        distance TEXT,
        dl_drop TEXT,
        dl_techniques TEXT,
        double_team TEXT,
        drive_end_event TEXT,
        drive_end_field_position TEXT,
        drive_end_play_number INTEGER,
        drive_start_event TEXT,
        drive_start_field_position TEXT,
        dropback_depth INTEGER,
        dropback_type TEXT,
        field_position TEXT,
        first_contact_player TEXT,
        forced_fumble TEXT,
        fumble TEXT,
        fumble_recovery TEXT,
        gain_loss INTEGER,
        gunners TEXT,
        hang_time REAL,
        hash TEXT,
        hash_defense TEXT,
        hit_players TEXT,
        hurry_players TEXT,
        incompletion_type TEXT,
        injured_on_play TEXT,
        interception TEXT,
        key_players TEXT,
        kick_contact TEXT,
        kick_depth TEXT,
        actual_kick_direction TEXT,
        intended_kick_direction TEXT,
        kicker TEXT,
        kick_result TEXT,
        kick_type TEXT,
        kick_width TEXT,
        kick_zone TEXT,
        linebacker_depth TEXT,
        missed_tackle TEXT,
        mofoc_played TEXT,
        mofoc_shown TEXT,
        negative_grade TEXT,
        offensive_formation TEXT,
        offensive_formation_group TEXT,
        offensive_oddities TEXT,
        offensive_personnel TEXT,
        offensive_personnel_basic TEXT,
        offensive_personnel_skill TEXT,
        offensive_players TEXT,
        offensive_player_ratings TEXT,
        offensive_substitutions TEXT,
        offense TEXT,
        on_los TEXT,
        operation_time REAL,
        pass_blocking_players TEXT,
        pass_breakup TEXT,
        pass_coverage TEXT,
        primary_pass_coverage TEXT,
        secondary_pass_coverage TEXT,
        pass_coverage_players TEXT,
        pass_depth TEXT,
        pass_direction TEXT,
        passer TEXT,
        pass_pattern TEXT,
        pass_pattern_basic TEXT,
        pass_pattern_by_player TEXT,
        pass_receiver_target_position TEXT, 
        pass_receiver_target TEXT,
        pass_result TEXT,
        pass_route_target TEXT,
        pass_route_target_group TEXT,
        pass_rush_players TEXT,
        pass_rush_result TEXT,
        pass_width TEXT,
        pass_zone TEXT,
        penalty TEXT,
        pistol TEXT,
        play_action_fake TEXT,
        play_end_field_position TEXT,
        actual_poa TEXT,
        poa_change_reason TEXT,
        intended_poa TEXT,
        positive_grade TEXT,
        press_players TEXT,
        pressure_detail TEXT,
        pump_fake TEXT,
        punt_rush TEXT,
        pursuit_players TEXT,
        quarterback TEXT,
        quaterback_moved_off_spot TEXT,
        quarterback_pressure TEXT,
        quarterback_pressure_allowed TEXT,
        quarterback_reset TEXT,
        quarterback_scramble TEXT,
        running_back_alignment TEXT,
        running_back_depth TEXT,
        running_back_direction TEXT,
        running_backs_in_backfield TEXT,
        intended_return_direction TEXT,
        return_direction TEXT,
        returner TEXT,
        tertiary_run_concept TEXT,
        secondary_run_concept TEXT,
        primary_run_concept TEXT,
        run_pass TEXT,
        sack TEXT,
        score_differential TEXT,
        shift_motion TEXT,
        shotgun INTEGER,
        special_teams_type TEXT,
        stop TEXT,
        st_safeties TEXT,
        tackle TEXT,
        assist TEXT,
        tight_end_alignment TEXT,
        touchdown TEXT,
        unblocked_pressure TEXT,
        wide_receiver_alignment TEXT,
        play_clock INTEGER,
        run_pass_option INTEGER
    );
    """

def create_game_command():
    return """
    CREATE TABLE game (
        id INTEGER PRIMARY KEY,
        gsis_id TEXT,
        league TEXT,
        season INTEGER,
        week INTEGER,
        start TEXT,
        kickoff_time TEXT,
        home_team TEXT,
        away_team TEXT,
        home_team_score INTEGER,
        away_team_score INTEGER,
        updated_at_timestamp INTEGER
    );
    """

def create_offense_command():
    return """
    CREATE TABLE offense (
        player_participation_id INTEGER,
        play_id INTEGER,
        gsis_play_id INTEGER,
        gsis_player_id TEXT,
        team TEXT,
        player_id INTEGER,
        versus_player_participation_id INTEGER,
        player_name TEXT,
        position TEXT,
        game_position TEXT,
        grade REAL,
        role TEXT,
        ball_carrier INTEGER,
        beaten_by_defender INTEGER,
        bunch INTEGER,
        caused_flag TEXT,
        comment TEXT,
        declined_penalty TEXT,
        dropback_depth INTEGER,
        dropback_type TEXT,
        dropped_pass INTEGER,
        forced_fumble INTEGER,
        fumble INTEGER,
        fumble_recovered INTEGER,
        hit_allowed INTEGER,
        hurry_allowed INTEGER,
        incompletion_type TEXT,
        injured_on_play INTEGER,
        interception INTEGER,
        lateral INTEGER,
        motion TEXT,
        offsetting_penalty TEXT,
        on_line_of_scrimmage INTEGER,
        pass_depth INTEGER,
        pass_direction TEXT,
        pass_result TEXT,
        pass_route TEXT,
        pass_route_depth INTEGER,
        pass_route_name TEXT,
        pass_route_target_group TEXT,
        pass_zone TEXT,
        passer INTEGER,
        passing_yards INTEGER,
        penalty TEXT,
        penalty_grade REAL,
        player_depth INTEGER,
        pressure_allowed INTEGER,
        press INTEGER,
        pump_fake INTEGER,
        quarterback INTEGER,
        running_back_direction TEXT,
        receiving_yards INTEGER,
        rushing_yards INTEGER,
        sack_allowed INTEGER,
        screen_block INTEGER,
        stance_type INTEGER,
        tackles_avoided INTEGER,
        targeted_receiver INTEGER,
        touchdown INTEGER,
        time_to_pressure REAL,
        time_to_throw REAL,
        wide_receiver_splits REAL,
        yards_after_catch INTEGER,
        yards_after_contact INTEGER
    );
    """

def create_defense_command():
    return """
    CREATE TABLE defense (
        player_participation_id INTEGER,
        play_id INTEGER,
        gsis_play_id INTEGER,
        gsis_player_id TEXT,
        team TEXT,
        player_id INTEGER,
        player_name TEXT,
        position TEXT,
        game_position TEXT,
        grade REAL,
        role TEXT,
        assist INTEGER,
        batted_pass INTEGER,
        box_player INTEGER,
        caused_flag TEXT,
        comment TEXT,
        declined_penalty TEXT,
        defensive_technique TEXT,
        dropped_interception INTEGER,
        first_contact_player INTEGER,
        first_contact_blocked INTEGER,
        forced_fumble INTEGER,
        fumble_recovered INTEGER,
        hit INTEGER,
        hurry INTEGER,
        injured_on_play INTEGER,
        interception INTEGER,
        missed_tackle INTEGER,
        missed_tackle_on_quarterback INTEGER,
        offsetting_penalty TEXT,
        pass_breakup INTEGER,
        penalty TEXT,
        penalty_grade REAL,
        player_dpeth INTEGER,
        press_coverage INTEGER,
        pressure INTEGER,
        primary_coverage INTEGER,
        pursuit INTEGER,
        sack INTEGER,
        secondary_coverage INTEGER,
        stop INTEGER,
        tackle INTEGER,
        touchdown INTEGER,
        unrecorded_pressure INTEGER
    );
    """

def create_specialteam_command():
    return """
    CREATE TABLE specialteam (
        player_participation_id INTEGER,
        play_id INTEGER,
        game_id INTEGER,
        gsis_player_id TEXT,
        team TEXT,
        player_id INTEGER,
        player_name TEXT,
        position TEXT,
        game_position TEXT,
        grade REAL,
        role TEXT,
        assist INTEGER,
        caused_flag TEXT,
        comment TEXT,
        creeper INTEGER,
        declined_penalty TEXT,
        double_teamed INTEGER,
        field_goal_result TEXT,
        forced_fumble INTEGER,
        fumble INTEGER,
        fumble_recovered INTEER,
        hang_time REAL,
        injured_on_play INTEGER,
        kick_depth INTEGER,
        kick_location TEXT,
        kick_result TEXT,
        kick_type TEXT,
        kick_width TEXT,
        kick_yards INTEGER,
        kicker INTEGER,
        kickoff_type TEXT,
        missed_tackle INTEGER,
        offsetting_penalty TEXT,
        onside_kick INTEGER,
        penalty TEXT,
        penalty_grade REAL,
        pre_kick_motion INTEGER,
        punt_contact_type TEXT,
        returner INTEGER,
        return_yards INTEGER,
        snap_detail TEXT,
        special_teams_type TEXT,
        tackle INTEGER,
        touchdown INTEGER
    );
    """

def main():
    cursor.execute(create_game_command())
    print(cursor.fetchall())
    cursor.execute(create_play_command())
    print(cursor.fetchall())
    cursor.execute(create_offense_command())
    print(cursor.fetchall())
    cursor.execute(create_defense_command())
    print(cursor.fetchall())
    cursor.execute(create_specialteam_command())
    print(cursor.fetchall())
    
## uncomment this to test the code
main()
connection.commit()
connection.close()